### PR TITLE
Added methods update class

### PR DESCRIPTION
**Pull request by nkauffm1**
I added the methods for the update class. There is a method to update the product inventory, a method to update the customer inventory, and two methods to update the product inventory to reflect customer orders. I tested the first, second, and fourth methods. The third method is meant to be called from the method that creates customer orders, so I am just waiting to test it out once create class is finalized.
I also updated the driver class to reflect the changes to the update class.
custOrder class was also updated.
I also moved the updateProducts method from the create class into the update class.

### CODE REVIEW

**Review by Matthew-Bustamante — APPROVED** [review]
Nice job everything worked on my end.  I liked how you took the user inputs out of the update method and put them into the driver method.  There was a conflict but I fixed it so it should be good to merge.

**Review by Matthew-Bustamante — APPROVED** [review]
Disregard the previous comment, Nathan will make the minor changes.

**Comment by Matthew-Bustamante** [comment]
Scratch the last comment I meant that one for a different pull request

**Review by jarell38 — APPROVED** [review]
yup everything looks good after this hopefully it will be easier to add new stuff to the project

**Pull request merged**
